# Generated by Django 5.2 on 2026-04-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=36, unique=True)),
                ('algorithm', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=100)),
                ('targets', models.JSONField()),
                ('input_features', models.JSONField()),
                ('all_cols', models.JSONField(default=list)),
                ('metrics', models.JSONField()),
                ('warnings', models.JSONField(default=list)),
                ('n_samples', models.IntegerField(default=0)),
                ('n_train', models.IntegerField(default=0)),
                ('n_val', models.IntegerField(default=0)),
                ('window_size', models.IntegerField(default=0)),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
